// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Article documents */
interface ArticleDocumentData {
    /**
     * Title field in *Article*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: article.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Author field in *Article*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: article.author
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    author: prismicT.RelationField;
    /**
     * Publication Date field in *Article*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: article.publication_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    publication_date: prismicT.DateField;
    /**
     * Featured Image field in *Article*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: article.featured_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    featured_image: prismicT.ImageField<never>;
}
/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ArticleDocumentData>, "article", Lang>;
/** Content for Author documents */
interface AuthorDocumentData {
    /**
     * Name field in *Author*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: author.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
}
/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;
/** Content for Event documents */
interface EventDocumentData {
    /**
     * Name field in *Event*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: event.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * Description field in *Event*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Start Date field in *Event*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: event.start_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    start_date: prismicT.TimestampField;
    /**
     * End Date field in *Event*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: event.end_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    end_date: prismicT.TimestampField;
}
/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;
/** Content for Restaurant documents */
interface RestaurantDocumentData {
    /**
     * Name field in *Restaurant*
     *
     * - **Field Type**: Title
     * - **Placeholder**: The restaurant’s name.
     * - **API ID Path**: restaurant.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * Featured Image field in *Restaurant*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: restaurant.featured_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    featured_image: prismicT.ImageField<never>;
    /**
     * Menu field in *Restaurant*
     *
     * - **Field Type**: Link
     * - **Placeholder**: A URL to the restaurant’s menu, such as a page or a PDF.
     * - **API ID Path**: restaurant.menu
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu: prismicT.LinkField;
    /**
     * Street Address field in *Restaurant*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The restaurant’s street address.
     * - **API ID Path**: restaurant.address_street
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    address_street: prismicT.KeyTextField;
    /**
     * Address Locality field in *Restaurant*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The restaurant’s city.
     * - **API ID Path**: restaurant.address_locality
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    address_locality: prismicT.KeyTextField;
    /**
     * Address Region field in *Restaurant*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The restaurant’s state.
     * - **API ID Path**: restaurant.address_region
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    address_region: prismicT.KeyTextField;
    /**
     * Address Postal Code field in *Restaurant*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The restaurant’s postal code.
     * - **API ID Path**: restaurant.address_postal_code
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    address_postal_code: prismicT.KeyTextField;
    /**
     * Address Country field in *Restaurant*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The restaurant’s country.
     * - **API ID Path**: restaurant.address_country
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    address_country: prismicT.KeyTextField;
}
/**
 * Restaurant document from Prismic
 *
 * - **API ID**: `restaurant`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RestaurantDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<RestaurantDocumentData>, "restaurant", Lang>;
export type AllDocumentTypes = ArticleDocument | AuthorDocument | EventDocument | RestaurantDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ArticleDocumentData, ArticleDocument, AuthorDocumentData, AuthorDocument, EventDocumentData, EventDocument, RestaurantDocumentData, RestaurantDocument, AllDocumentTypes };
    }
}
